export const locationArray = [
  {
    stationId: 1,
    name: "Alpha",
    location: "Pto. Rivas Ibaba",
    area: "Balanga City, Bataan",
    temperature: 20,
    heatIndex: 30,
    humidity: 40,
    precipitation: 100,
    airPressure: 1000,
    windSpeed: 4.61,
    windDirection: 75,
    gust: 0,
    uvIndex: 1,
    irradiance: 40000,
    lux: 5400,
    batteryLevel: 90,
    weather: "Clear",
  },
  {
    stationId: 2,
    location: "Pag-asa",
    area: "Bagac, Bataan",
    temperature: 30,
    heatIndex: 37,
    humidity: 25,
    precipitation: 508,
    airPressure: 2034,
    windSpeed: 4.61,
    windDirection: 100.5,
    gust: 0,
    uvIndex: 1,
    irradiance: 40000,
    lux: 5400,
    batteryLevel: 35,
    weather: "Clear",
  },
  {
    stationId: 3,
    location: "Sisiman",
    area: "Mariveles, Bataan",
    temperature: 24,
    heatIndex: 63,
    humidity: 9,
    precipitation: 50,
    airPressure: 231,
    windSpeed: 3.2,
    windDirection: 360,
    gust: 0,
    uvIndex: 3,
    irradiance: 400,
    lux: 500,
    batteryLevel: 25,
    weather: "Clear",
  },
  {
    stationId: 4,
    location: "Bayan-bayanan",
    area: "Dinalupihan, Bataan",
    temperature: 60,
    heatIndex: 65,
    humidity: 30,
    precipitation: 948,
    airPressure: 1234,
    windSpeed: 534.2,
    windDirection: 270,
    gust: 0,
    uvIndex: 1,
    irradiance: 40000,
    lux: 5400,
    batteryLevel: 69,
    weather: "Clear",
  },

  {
    stationId: 5,
    location: "Townsite",
    area: "Limay, Bataan",
    temperature: 153,
    heatIndex: 234,
    humidity: 2352,
    precipitation: 2345,
    airPressure: 62341,
    windSpeed: 342.234,
    windDirection: 180,
    gust: 0,
    uvIndex: 1,
    irradiance: 40000,
    lux: 5400,
    batteryLevel: 78,
    weather: "Clear",
  },
  {
    stationId: 6,
    name: "Foxtrot",
    location: "Abucay, Bataan",
    area: "Balanga City, Bataan",
    temperature: 20,
    heatIndex: 30,
    humidity: 40,
    precipitation: 100,
    airPressure: 1000,
    windSpeed: 4.61,
    windDirection: 75,
    gust: 0,
    uvIndex: 1,
    irradiance: 40000,
    lux: 5400,
    batteryLevel: 56,
    weather: "Clear",
  },
];

export const dailySuggestionArray = [
  {
    title: "Umbrellas",
    description: "Highly suggested",
    imageSrc: "/assets/dailyIcons/umbrella.svg",
    altText: "Umbrella",
    color: "green-500",
  },
  {
    title: "Refreshments",
    description: "Highly suggested",
    imageSrc: "/assets/dailyIcons/bottle.svg",
    altText: "Refreshment",
    color: "green-500",
  },
  {
    title: "Sunscreen",
    description: "Highly suggested",
    imageSrc: "/assets/dailyIcons/sunscreen.svg",
    altText: "Sunscreen",
    color: "green-500",
  },
  {
    title: "Clothing",
    description: "Highly suggested",
    imageSrc: "/assets/dailyIcons/clothing.svg",
    altText: "Clothing",
    color: "yellow-500",
  },
  {
    title: "Driving Conditions",
    description: "Safe",
    imageSrc: "/assets/dailyIcons/car.svg",
    altText: "Car",
    color: "green-500",
  },
  {
    title: "Heat Stroke",
    description: "Danger",
    imageSrc: "/assets/dailyIcons/temp.svg",
    altText: "Temp",
    color: "red-500",
  },
];

export const dailyActivityArray = [
  {
    title: "Jogging",
    description: "Highly suggested",
    imageSrc: "/assets/dailyIcons/jog.svg",
    altText: "Jog",
    color: "green-500",
  },
  {
    title: "Cycling",
    description: "Highly suggested",
    imageSrc: "/assets/dailyIcons/cycle.svg",
    altText: "Cycle",
    color: "green-500",
  },
  {
    title: "Swimming",
    description: "Highly suggested",
    imageSrc: "/assets/dailyIcons/swim.svg",
    altText: "Swim",
    color: "green-500",
  },
  {
    title: "Camping",
    description: "Highly suggested",
    imageSrc: "/assets/dailyIcons/camp.svg",
    altText: "Camp",
    color: "yellow-500",
  },
  {
    title: "Sports",
    description: "Safe",
    imageSrc: "/assets/dailyIcons/ball.svg",
    altText: "Sports",
    color: "green-500",
  },
];
