import { LocationProvider } from "../context/locationContext";
import { ParameterProvider } from "../context/parametersContext";

import type { Metadata } from "next";
import "./globals.css";
import { Montserrat } from "next/font/google";
import Header from "@/components/shared/header";

const montserrat = Montserrat({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={montserrat.className}>
        <LocationProvider>
          <ParameterProvider>
            <Header />
            {children}
          </ParameterProvider>
        </LocationProvider>
      </body>
    </html>
  );
}
